### PR TITLE
Noam initial site app

### PR DESCRIPTION
**Pull request by noless-zz**
added some more stuff

### CODE REVIEW

**Comment by GlobeProgger** [comment]
Don't you want to complete the "Getting Started with Rails" b4 we merge?

**Comment by noless-zz** [comment]
na its a fun practice to merge the progress... but im done now with the delete so you can merge

**Comment by GlobeProgger** [comment]
Is there any way I can test your pull request b4 I merge?

**Comment by noless-zz** [comment]
ya, just pull my repo in a seperate folder and run from there...
there are many other ways?!?!

**Pull request merged**
