### PR TITLE
add saving for form in db

### PR DESCRIPTION
**Pull request by noless-zz**
show enties of db
no browsing of db yet

### CODE REVIEW

**Comment by noless-zz** [comment]
if you wait a few more hours i'll have it further along... :)

**Comment by GlobeProgger** [comment]
Cool. I'll have a look in the evening

**Comment by noless-zz** [comment]
works nice the pull request, i do all the work... you just have to merge in your code ;) we'll see how we start managing colitions

**Comment by GlobeProgger** [comment]
Yeah just merged it fine. Cant test it yet though

**Comment by GlobeProgger** [comment]
Was looking @ [Heroku](https://dashboard.heroku.com) for hosting. Seems a good choice. 1 Dyno is free.

**Pull request merged**
